version: '3.9'
services:

  pgsql:
    image: postgres:latest
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - 15432:15432
    volumes:
      - ./data:/var/lib/postgresql/data
